# alertmanager-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      receiver: mcp-healer

    receivers:
      - name: mcp-healer
        webhook_configs:
          - url: "http://mcp-server.mcp.svc.cluster.local:9000/mcp/heal/auto"
            send_resolved: true
