apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alert-rules
  namespace: monitoring
data:
  alert.rules.yml: |
    groups:
    - name: pod-alerts
      rules:
      - alert: PodNotReadyOrCrashLooping
        expr: kube_pod_container_status_restarts_total{job="kube-state-metrics", namespace="default"} > 3
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: "Pod {{ $labels.pod }} in default namespace is failing or crashlooping"
          description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} has restarted more than 3 times in the last 3 minutes."
          mcp_namespace: "{{ $labels.namespace }}"
          mcp_deployment: "ai-detector"
          mcp_pod: "{{ $labels.pod }}"
