apiVersion: v1
kind: Service
metadata:
  name: ai-detector-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8000"
spec:
  selector:
    app: ai-detector
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000