apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: mcp-pod-exec-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mcp-pod-exec-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: mcp-service-account
    namespace: mcp
roleRef:
  kind: Role
  name: mcp-pod-exec-role
  apiGroup: rbac.authorization.k8s.io
