apiVersion: v1
kind: PersistentVolume
metadata:
  name: mcp-logs-pv
  namespace: mcp
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:                        
    path: /mnt/data/mcp-logs        

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mcp-logs-pvc
  namespace: mcp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
