apiVersion: v1
kind: Service
metadata:
  name: mcp-server
  namespace: mcp
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8001"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: mcp-server
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: metrics
      protocol: TCP
      port: 8001
      targetPort: 8001
